In [20]:
import os
print(os.getcwd())

c:\Users\abish\OneDrive\New\OneDrive\Desktop\Airlines\Notebooks

In [21]:
from pathlib import Path
import pandas as pd

file_path = Path("../Data/OTP_APR2026.csv")

df = pd.read_csv(file_path, low_memory=False)
df.columns = df.columns.str.strip()

In [22]:
print("Rows:", df.shape[0])
print("Columns:", df.shape[1])
print("Date range:", df["FlightDate"].min(), "to", df["FlightDate"].max())
print("Years:", df["Year"].unique())
print("Months:", df["Month"].unique())

Rows: 660674
Columns: 120
Date range: 2026-04-01 to 2026-04-30
Years: [2026]
Months: [4]

In [23]:
# Basic information
df.info()

# First 5 rows
df.head()

# Last 5 rows
df.tail()

# Random 5 rows
df.sample(5)

<class 'pandas.DataFrame'>
RangeIndex: 660674 entries, 0 to 660673
Columns: 120 entries, Year to Unnamed: 119
dtypes: float64(72), int64(23), str(25)
memory usage: 604.9 MB

,Year,Quarter,Month,DayofMonth,DayOfWeek,FlightDate,Marketing_Airline_Network,Operated_or_Branded_Code_Share_Partners,DOT_ID_Marketing_Airline,IATA_Code_Marketing_Airline,Flight_Number_Marketing_Airline,Originally_Scheduled_Code_Share_Airline,DOT_ID_Originally_Scheduled_Code_Share_Airline,IATA_Code_Originally_Scheduled_Code_Share_Airline,Flight_Num_Originally_Scheduled_Code_Share_Airline,Operating_Airline,DOT_ID_Operating_Airline,IATA_Code_Operating_Airline,Tail_Number,Flight_Number_Operating_Airline,OriginAirportID,OriginAirportSeqID,OriginCityMarketID,Origin,OriginCityName,OriginState,OriginStateFips,OriginStateName,OriginWac,DestAirportID,DestAirportSeqID,DestCityMarketID,Dest,DestCityName,DestState,DestStateFips,DestStateName,DestWac,CRSDepTime,DepTime,DepDelay,DepDelayMinutes,DepDel15,DepartureDelayGroups,DepTimeBlk,TaxiOut,WheelsOff,WheelsOn,TaxiIn,CRSArrTime,ArrTime,ArrDelay,ArrDelayMinutes,ArrDel15,ArrivalDelayGroups,ArrTimeBlk,Cancelled,CancellationCode,Diverted,CRSElapsedTime,ActualElapsedTime,AirTime,Flights,Distance,DistanceGroup,CarrierDelay,WeatherDelay,NASDelay,SecurityDelay,LateAircraftDelay,FirstDepTime,TotalAddGTime,LongestAddGTime,DivAirportLandings,DivReachedDest,DivActualElapsedTime,DivArrDelay,DivDistance,Div1Airport,Div1AirportID,Div1AirportSeqID,Div1WheelsOn,Div1TotalGTime,Div1LongestGTime,Div1WheelsOff,Div1TailNum,Div2Airport,Div2AirportID,Div2AirportSeqID,Div2WheelsOn,Div2TotalGTime,Div2LongestGTime,Div2WheelsOff,Div2TailNum,Div3Airport,Div3AirportID,Div3AirportSeqID,Div3WheelsOn,Div3TotalGTime,Div3LongestGTime,Div3WheelsOff,Div3TailNum,Div4Airport,Div4AirportID,Div4AirportSeqID,Div4WheelsOn,Div4TotalGTime,Div4LongestGTime,Div4WheelsOff,Div4TailNum,Div5Airport,Div5AirportID,Div5AirportSeqID,Div5WheelsOn,Div5TotalGTime,Div5LongestGTime,Div5WheelsOff,Div5TailNum,Duplicate,Unnamed: 119
471736,2026,2,4,14,2,2026-04-14,AA,AA_CODESHARE,19805,AA,3906,NaN,NaN,NaN,NaN,MQ,20398,MQ,N219NN,3906,15919,1591905,31834,XNA,"Fayetteville, AR",AR,5,Arkansas,71,13930,1393008,30977,ORD,"Chicago, IL",IL,17,Illinois,41,1608,1711.0,63.0,63.0,1.0,4.0,1600-1659,20.0,1731.0,1849.0,15.0,1816,1904.0,48.0,48.0,1.0,3.0,1800-1859,0.0,NaN,0.0,128.0,113.0,78.0,1.0,522.0,3,0.0,0.0,0.0,0.0,48.0,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN
249683,2026,2,4,22,3,2026-04-22,AA,AA,19805,AA,2677,NaN,NaN,NaN,NaN,AA,19805,AA,N315PE,2677,13303,1330304,32467,MIA,"Miami, FL",FL,12,Florida,33,14107,1410703,30466,PHX,"Phoenix, AZ",AZ,4,Arizona,81,950,942.0,-8.0,0.0,0.0,-1.0,0900-0959,12.0,954.0,1117.0,4.0,1154,1121.0,-33.0,0.0,0.0,-2.0,1100-1159,0.0,NaN,0.0,304.0,279.0,263.0,1.0,1972.0,8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN
631544,2026,2,4,26,7,2026-04-26,UA,UA,19977,UA,1349,NaN,NaN,NaN,NaN,UA,19977,UA,N37267,1349,13930,1393008,30977,ORD,"Chicago, IL",IL,17,Illinois,41,14122,1412202,30198,PIT,"Pittsburgh, PA",PA,42,Pennsylvania,23,1410,1403.0,-7.0,0.0,0.0,-1.0,1400-1459,32.0,1435.0,1632.0,4.0,1650,1636.0,-14.0,0.0,0.0,-1.0,1600-1659,0.0,NaN,0.0,100.0,93.0,57.0,1.0,413.0,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN
35455,2026,2,4,17,5,2026-04-17,WN,WN,19393,WN,1923,NaN,NaN,NaN,NaN,WN,19393,WN,N8897K,1923,11697,1169707,32467,FLL,"Fort Lauderdale, FL",FL,12,Florida,33,13232,1323202,30977,MDW,"Chicago, IL",IL,17,Illinois,41,655,652.0,-3.0,0.0,0.0,-1.0,0600-0659,21.0,713.0,858.0,6.0,905,904.0,-1.0,0.0,0.0,-1.0,0900-0959,0.0,NaN,0.0,190.0,192.0,165.0,1.0,1167.0,5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN
103500,2026,2,4,28,2,2026-04-28,WN,WN,19393,WN,1562,NaN,NaN,NaN,NaN,WN,19393,WN,N266WN,1562,15304,1530402,33195,TPA,"Tampa, FL",FL,12,Florida,33,10599,1059904,30599,BHM,"Birmingham, AL",AL,1,Alabama,51,955,951.0,-4.0,0.0,0.0,-1.0,0900-0959,14.0,1005.0,1034.0,4.0,1030,1038.0,8.0,8.0,0.0,0.0,1000-1059,0.0,NaN,0.0,95.0,107.0,89.0,1.0,459.0,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN

In [24]:
df.info(show_counts=True)

<class 'pandas.DataFrame'>
RangeIndex: 660674 entries, 0 to 660673
Columns: 120 entries, Year to Unnamed: 119
dtypes: float64(72), int64(23), str(25)
memory usage: 604.9 MB

In [25]:
import pandas as pd

pd.set_option("display.max_columns", None)
pd.set_option("display.max_rows", None)

df.info(verbose=True, show_counts=True)

<class 'pandas.DataFrame'>
RangeIndex: 660674 entries, 0 to 660673
Data columns (total 120 columns):
 #    Column                                              Non-Null Count   Dtype
---   ------                                              --------------   -----
 0    Year                                                660674 non-null  int64
 1    Quarter                                             660674 non-null  int64
 2    Month                                               660674 non-null  int64
 3    DayofMonth                                          660674 non-null  int64
 4    DayOfWeek                                           660674 non-null  int64
 5    FlightDate                                          660674 non-null  str
 6    Marketing_Airline_Network                           660674 non-null  str
 7    Operated_or_Branded_Code_Share_Partners             660674 non-null  str
 8    DOT_ID_Marketing_Airline                            660674 non-null  int64
 9    IATA_Code_Marketing_Airline                         660674 non-null  str
 10   Flight_Number_Marketing_Airline                     660674 non-null  int64
 11   Originally_Scheduled_Code_Share_Airline             56 non-null      str
 12   DOT_ID_Originally_Scheduled_Code_Share_Airline      56 non-null      float64
 13   IATA_Code_Originally_Scheduled_Code_Share_Airline   56 non-null      str
 14   Flight_Num_Originally_Scheduled_Code_Share_Airline  56 non-null      float64
 15   Operating_Airline                                   660674 non-null  str
 16   DOT_ID_Operating_Airline                            660674 non-null  int64
 17   IATA_Code_Operating_Airline                         660674 non-null  str
 18   Tail_Number                                         659805 non-null  str
 19   Flight_Number_Operating_Airline                     660674 non-null  int64
 20   OriginAirportID                                     660674 non-null  int64
 21   OriginAirportSeqID                                  660674 non-null  int64
 22   OriginCityMarketID                                  660674 non-null  int64
 23   Origin                                              660674 non-null  str
 24   OriginCityName                                      660674 non-null  str
 25   OriginState                                         660674 non-null  str
 26   OriginStateFips                                     660674 non-null  int64
 27   OriginStateName                                     660674 non-null  str
 28   OriginWac                                           660674 non-null  int64
 29   DestAirportID                                       660674 non-null  int64
 30   DestAirportSeqID                                    660674 non-null  int64
 31   DestCityMarketID                                    660674 non-null  int64
 32   Dest                                                660674 non-null  str
 33   DestCityName                                        660674 non-null  str
 34   DestState                                           660674 non-null  str
 35   DestStateFips                                       660674 non-null  int64
 36   DestStateName                                       660674 non-null  str
 37   DestWac                                             660674 non-null  int64
 38   CRSDepTime                                          660674 non-null  int64
 39   DepTime                                             655122 non-null  float64
 40   DepDelay                                            655066 non-null  float64
 41   DepDelayMinutes                                     655066 non-null  float64
 42   DepDel15                                            655066 non-null  float64
 43   DepartureDelayGroups                                655066 non-null  float64
 44   DepTimeBlk                                          660674 non-null  str
 45   TaxiOut                                             654850 non-null  float64
 46   WheelsOff                                           654850 non-null  float64
 47   WheelsOn                                            654638 non-null  float64
 48   TaxiIn                                              654638 non-null  float64
 49   CRSArrTime                                          660674 non-null  int64
 50   ArrTime                                             654638 non-null  float64
 51   ArrDelay                                            653335 non-null  float64
 52   ArrDelayMinutes                                     653335 non-null  float64
 53   ArrDel15                                            653335 non-null  float64
 54   ArrivalDelayGroups                                  653335 non-null  float64
 55   ArrTimeBlk                                          660674 non-null  str
 56   Cancelled                                           660674 non-null  float64
 57   CancellationCode                                    5877 non-null    str
 58   Diverted                                            660674 non-null  float64
 59   CRSElapsedTime                                      660674 non-null  float64
 60   ActualElapsedTime                                   653335 non-null  float64
 61   AirTime                                             653335 non-null  float64
 62   Flights                                             660674 non-null  float64
 63   Distance                                            660674 non-null  float64
 64   DistanceGroup                                       660674 non-null  int64
 65   CarrierDelay                                        130203 non-null  float64
 66   WeatherDelay                                        130203 non-null  float64
 67   NASDelay                                            130203 non-null  float64
 68   SecurityDelay                                       130203 non-null  float64
 69   LateAircraftDelay                                   130203 non-null  float64
 70   FirstDepTime                                        4390 non-null    float64
 71   TotalAddGTime                                       4384 non-null    float64
 72   LongestAddGTime                                     4384 non-null    float64
 73   DivAirportLandings                                  660674 non-null  int64
 74   DivReachedDest                                      1462 non-null    float64
 75   DivActualElapsedTime                                1303 non-null    float64
 76   DivArrDelay                                         1303 non-null    float64
 77   DivDistance                                         1462 non-null    float64
 78   Div1Airport                                         1535 non-null    str
 79   Div1AirportID                                       1535 non-null    float64
 80   Div1AirportSeqID                                    1535 non-null    float64
 81   Div1WheelsOn                                        1535 non-null    float64
 82   Div1TotalGTime                                      1535 non-null    float64
 83   Div1LongestGTime                                    1535 non-null    float64
 84   Div1WheelsOff                                       1328 non-null    float64
 85   Div1TailNum                                         1328 non-null    str
 86   Div2Airport                                         8 non-null       str
 87   Div2AirportID                                       8 non-null       float64
 88   Div2AirportSeqID                                    8 non-null       float64
 89   Div2WheelsOn                                        8 non-null       float64
 90   Div2TotalGTime                                      8 non-null       float64
 91   Div2LongestGTime                                    8 non-null       float64
 92   Div2WheelsOff                                       3 non-null       float64
 93   Div2TailNum                                         3 non-null       str
 94   Div3Airport                                         0 non-null       float64
 95   Div3AirportID                                       0 non-null       float64
 96   Div3AirportSeqID                                    0 non-null       float64
 97   Div3WheelsOn                                        0 non-null       float64
 98   Div3TotalGTime                                      0 non-null       float64
 99   Div3LongestGTime                                    0 non-null       float64
 100  Div3WheelsOff                                       0 non-null       float64
 101  Div3TailNum                                         0 non-null       float64
 102  Div4Airport                                         0 non-null       float64
 103  Div4AirportID                                       0 non-null       float64
 104  Div4AirportSeqID                                    0 non-null       float64
 105  Div4WheelsOn                                        0 non-null       float64
 106  Div4TotalGTime                                      0 non-null       float64
 107  Div4LongestGTime                                    0 non-null       float64
 108  Div4WheelsOff                                       0 non-null       float64
 109  Div4TailNum                                         0 non-null       float64
 110  Div5Airport                                         0 non-null       float64
 111  Div5AirportID                                       0 non-null       float64
 112  Div5AirportSeqID                                    0 non-null       float64
 113  Div5WheelsOn                                        0 non-null       float64
 114  Div5TotalGTime                                      0 non-null       float64
 115  Div5LongestGTime                                    0 non-null       float64
 116  Div5WheelsOff                                       0 non-null       float64
 117  Div5TailNum                                         0 non-null       float64
 118  Duplicate                                           660674 non-null  str
 119  Unnamed: 119                                        0 non-null       float64
dtypes: float64(72), int64(23), str(25)
memory usage: 604.9 MB

In [26]:
missing = pd.DataFrame({
    "Non-Null Count": df.count(),
    "Missing": df.isna().sum(),
    "Dtype": df.dtypes
})

missing

,Non-Null Count,Missing,Dtype
Year,660674,0,int64
Quarter,660674,0,int64
Month,660674,0,int64
DayofMonth,660674,0,int64
DayOfWeek,660674,0,int64
FlightDate,660674,0,str
Marketing_Airline_Network,660674,0,str
Operated_or_Branded_Code_Share_Partners,660674,0,str
DOT_ID_Marketing_Airline,660674,0,int64
IATA_Code_Marketing_Airline,660674,0,str
Flight_Number_Marketing_Airline,660674,0,int64
Originally_Scheduled_Code_Share_Airline,56,660618,str
DOT_ID_Originally_Scheduled_Code_Share_Airline,56,660618,float64
IATA_Code_Originally_Scheduled_Code_Share_Airline,56,660618,str
Flight_Num_Originally_Scheduled_Code_Share_Airline,56,660618,float64
Operating_Airline,660674,0,str
DOT_ID_Operating_Airline,660674,0,int64
IATA_Code_Operating_Airline,660674,0,str
Tail_Number,659805,869,str
Flight_Number_Operating_Airline,660674,0,int64
OriginAirportID,660674,0,int64
OriginAirportSeqID,660674,0,int64
OriginCityMarketID,660674,0,int64
Origin,660674,0,str
OriginCityName,660674,0,str
OriginState,660674,0,str
OriginStateFips,660674,0,int64
OriginStateName,660674,0,str
OriginWac,660674,0,int64
DestAirportID,660674,0,int64
DestAirportSeqID,660674,0,int64
DestCityMarketID,660674,0,int64
Dest,660674,0,str
DestCityName,660674,0,str
DestState,660674,0,str
DestStateFips,660674,0,int64
DestStateName,660674,0,str
DestWac,660674,0,int64
CRSDepTime,660674,0,int64
DepTime,655122,5552,float64
DepDelay,655066,5608,float64
DepDelayMinutes,655066,5608,float64
DepDel15,655066,5608,float64
DepartureDelayGroups,655066,5608,float64
DepTimeBlk,660674,0,str
TaxiOut,654850,5824,float64
WheelsOff,654850,5824,float64
WheelsOn,654638,6036,float64
TaxiIn,654638,6036,float64
CRSArrTime,660674,0,int64
ArrTime,654638,6036,float64
ArrDelay,653335,7339,float64
ArrDelayMinutes,653335,7339,float64
ArrDel15,653335,7339,float64
ArrivalDelayGroups,653335,7339,float64
ArrTimeBlk,660674,0,str
Cancelled,660674,0,float64
CancellationCode,5877,654797,str
Diverted,660674,0,float64
CRSElapsedTime,660674,0,float64
ActualElapsedTime,653335,7339,float64
AirTime,653335,7339,float64
Flights,660674,0,float64
Distance,660674,0,float64
DistanceGroup,660674,0,int64
CarrierDelay,130203,530471,float64
WeatherDelay,130203,530471,float64
NASDelay,130203,530471,float64
SecurityDelay,130203,530471,float64
LateAircraftDelay,130203,530471,float64
FirstDepTime,4390,656284,float64
TotalAddGTime,4384,656290,float64
LongestAddGTime,4384,656290,float64
DivAirportLandings,660674,0,int64
DivReachedDest,1462,659212,float64
DivActualElapsedTime,1303,659371,float64
DivArrDelay,1303,659371,float64
DivDistance,1462,659212,float64
Div1Airport,1535,659139,str
Div1AirportID,1535,659139,float64
Div1AirportSeqID,1535,659139,float64
Div1WheelsOn,1535,659139,float64
Div1TotalGTime,1535,659139,float64
Div1LongestGTime,1535,659139,float64
Div1WheelsOff,1328,659346,float64
Div1TailNum,1328,659346,str
Div2Airport,8,660666,str
Div2AirportID,8,660666,float64
Div2AirportSeqID,8,660666,float64
Div2WheelsOn,8,660666,float64
Div2TotalGTime,8,660666,float64
Div2LongestGTime,8,660666,float64
Div2WheelsOff,3,660671,float64
Div2TailNum,3,660671,str
Div3Airport,0,660674,float64
Div3AirportID,0,660674,float64
Div3AirportSeqID,0,660674,float64
Div3WheelsOn,0,660674,float64
Div3TotalGTime,0,660674,float64
Div3LongestGTime,0,660674,float64
Div3WheelsOff,0,660674,float64
Div3TailNum,0,660674,float64
Div4Airport,0,660674,float64
Div4AirportID,0,660674,float64
Div4AirportSeqID,0,660674,float64
Div4WheelsOn,0,660674,float64
Div4TotalGTime,0,660674,float64
Div4LongestGTime,0,660674,float64
Div4WheelsOff,0,660674,float64
Div4TailNum,0,660674,float64
Div5Airport,0,660674,float64
Div5AirportID,0,660674,float64
Div5AirportSeqID,0,660674,float64
Div5WheelsOn,0,660674,float64
Div5TotalGTime,0,660674,float64
Div5LongestGTime,0,660674,float64
Div5WheelsOff,0,660674,float64
Div5TailNum,0,660674,float64
Duplicate,660674,0,str
Unnamed: 119,0,660674,float64

In [27]:
df = df.drop(columns=["Unnamed: 119"])

In [28]:
print(df.shape)

(660674, 119)

In [29]:
print("Duplicate rows:", df.duplicated().sum())

Duplicate rows: 0

In [30]:
# Keep only Southwest flights
wn = df[df["Marketing_Airline_Network"] == "WN"].copy()

print("Southwest flights:", len(wn))
print("Unique aircraft:", wn["Tail_Number"].nunique())

Southwest flights: 117814
Unique aircraft: 787

In [31]:
tail_counts = (
    wn["Tail_Number"]
    .value_counts()
    .reset_index()
)

tail_counts.columns = ["Tail_Number", "Flights"]

tail_counts.head(10)

  Tail_Number  Flights
0      N227WN      195
1      N246LV      191
2      N7844A      187
3      N931WN      184
4      N957WN      184
5      N561WN      183
6      N939WN      183
7      N436WN      183
8      N965WN      183
9      N920WN      182

In [32]:
tail = "N7844A"

In [33]:
aircraft = wn[wn["Tail_Number"] == tail].copy()

print(aircraft.shape)

(187, 119)

In [34]:
aircraft = aircraft.sort_values(
    ["FlightDate", "CRSDepTime"]
)

aircraft[
    [
        "FlightDate",
        "Origin",
        "Dest",
        "Flight_Number_Marketing_Airline",
        "Tail_Number",
        "DepDelay",
        "ArrDelay"
    ]
].head(20)

,FlightDate,Origin,Dest,Flight_Number_Marketing_Airline,Tail_Number,DepDelay,ArrDelay
17352,2026-04-01,DCA,STL,3151,N7844A,-8.0,-20.0
20022,2026-04-01,STL,PBI,3312,N7844A,-3.0,1.0
19086,2026-04-01,PBI,ISP,3928,N7844A,0.0,0.0
17931,2026-04-01,ISP,MCO,3445,N7844A,8.0,0.0
18544,2026-04-01,MCO,RSW,853,N7844A,13.0,-1.0
23554,2026-04-02,RSW,IND,2794,N7844A,12.0,-6.0
21877,2026-04-02,IND,PHX,2794,N7844A,0.0,-3.0
23222,2026-04-02,PHX,BUR,2794,N7844A,15.0,5.0
20691,2026-04-02,BUR,SJC,856,N7844A,6.0,-3.0
23834,2026-04-02,SJC,BUR,1313,N7844A,1.0,-4.0
20652,2026-04-02,BUR,ABQ,1312,N7844A,-3.0,-10.0
20194,2026-04-02,ABQ,PHX,2399,N7844A,5.0,14.0
23352,2026-04-02,PHX,SAN,2837,N7844A,22.0,19.0
50517,2026-04-03,SAN,LAS,3966,N7844A,-5.0,-23.0
48972,2026-04-03,LAS,ONT,384,N7844A,13.0,-1.0
50009,2026-04-03,ONT,SMF,384,N7844A,-5.0,-22.0
50895,2026-04-03,SMF,ONT,3452,N7844A,5.0,-2.0
50005,2026-04-03,ONT,SJC,752,N7844A,-2.0,-5.0
50756,2026-04-03,SJC,LGB,2339,N7844A,0.0,-11.0
49241,2026-04-03,LGB,SMF,3781,N7844A,-6.0,-24.0

In [37]:
wn = df[df["Operating_Airline"] == "WN"].copy()

print("Southwest flights:", len(wn))
print("Unique aircraft:", wn["Tail_Number"].nunique())

Southwest flights: 117814
Unique aircraft: 787

In [38]:
apr1 = aircraft[aircraft["FlightDate"] == "2026-04-01"].copy()

print("Flights on April 1:", len(apr1))

apr1 = apr1.sort_values("CRSDepTime")

apr1[
    [
        "CRSDepTime",
        "DepTime",
        "Origin",
        "Dest",
        "Flight_Number_Marketing_Airline",
        "DepDelay",
        "ArrDelay",
        "Tail_Number"
    ]
]

Flights on April 1: 5

,CRSDepTime,DepTime,Origin,Dest,Flight_Number_Marketing_Airline,DepDelay,ArrDelay,Tail_Number
17352,800,752.0,DCA,STL,3151,-8.0,-20.0,N7844A
20022,950,947.0,STL,PBI,3312,-3.0,1.0,N7844A
19086,1405,1405.0,PBI,ISP,3928,0.0,0.0,N7844A
17931,1725,1733.0,ISP,MCO,3445,8.0,0.0,N7844A
18544,2105,2118.0,MCO,RSW,853,13.0,-1.0,N7844A